version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: ecommerce-minio
    ports:
      - "9000:9000"  # API Port
      - "9100:9001"  # Console Port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - ecommerce-network

  # SQL Server service có thể thêm sau nếu cần

networks:
  ecommerce-network:
    driver: bridge

volumes:
  minio_data:
  redis_data: 